<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="30.310" tests="3" failures="2">
  <testsuite name="Root Suite" timestamp="2023-06-12T19:55:25" tests="0" file="cypress\e2e\API\pierwszyTestApi.js" time="0.000" failures="0">
  </testsuite>
  <testsuite name="E2E - Testy Api" timestamp="2023-06-12T19:55:25" tests="3" time="30.221" failures="2">
    <testcase name="E2E - Testy Api Weryfikacja tagów API" time="2.532" classname="Weryfikacja tagów API">
    </testcase>
    <testcase name="E2E - Testy Api Niepoprawne logowanie Logowania" time="4.158" classname="Niepoprawne logowanie Logowania">
      <failure message="Timed out retrying after 4000ms: Expected to find element: `a.nav-link`, but never found it." type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: Expected to find element: `a.nav-link`, but never found it.
    at Context.eval (webpack:///./cypress/e2e/API/pierwszyTestApi.js:22:11)]]></failure>
    </testcase>
    <testcase name="E2E - Testy Api Poprawne logowanie" time="4.189" classname="Poprawne logowanie">
      <failure message="Timed out retrying after 4000ms: Expected to find element: `[placeholder=&quot;Email&quot;]`, but never found it." type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: Expected to find element: `[placeholder="Email"]`, but never found it.
    at Context.eval (webpack:///./cypress/support/commands.js:31:7)]]></failure>
    </testcase>
  </testsuite>
</testsuites>